# Generated by Django 2.2.2 on 2021-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='luffy_user',
        ),
    ]
